# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :buildanddeployfree do
    gym(scheme: "sobotta-free")
    pilot
  end



  lane :buildanddeployfull do
    gym(scheme: "sobotta-full")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore2 do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "meetyourfriends") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

lane :refresh_dsyms do
  BUILD_NUMBER = get_build_number(xcodeproj: "sobottaprototype.xcodeproj")                    # Download dSYM files from iT
  download_dsyms(build_number: BUILD_NUMBER)                   # Download dSYM files from iTC
  upload_symbols_to_crashlytics(api_token:"daed8da2015bb74fed78cfe0b070ca09bec546a1")   # Upload them to Crashlytics
end

lane :incit do
increment_build_number
end

lane :full do
ENV["APP_IDENTIFIER"] = "com.austrianapps.ios.elsevier.sobottafull"
	increment_build_number
	git_commit(path:["sobottaprototype/sobotta-free-Info.plist","sobottaprototype/sobottaprototype-Info.plist","sobottaprototype.xcodeproj/project.pbxproj"],message:"version increased")
    push_to_git_remote
	buildanddeployfull
	refresh_dsyms
end

lane :free do
ENV["APP_IDENTIFIER"] = "com.austrianapps.ios.elsevier.sobottafree"
	increment_build_number
	git_commit(path:["sobottaprototype/sobotta-free-Info.plist","sobottaprototype/sobottaprototype-Info.plist","sobottaprototype.xcodeproj/project.pbxproj"],message:"version increased")
    push_to_git_remote
	buildanddeployfree
	refresh_dsyms
end



end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
